CREATE TABLE user(
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户名',
  password VARCHAR(64) NOT NULL DEFAULT '' COMMENT '密码',
  nickname VARCHAR(32) COMMENT '昵称',
  sex TINYINT DEFAULT 0 COMMENT '性别 0女 1男',
  email VARCHAR(64) COMMENT '邮箱',
  is_deleted TINYINT DEFAULT 0 COMMENT '是否删除 0未删除 1删除',
  create_time DATETIME  DEFAULT '0001-01-01 00:00:00' COMMENT '创建时间',
  update_time DATETIME  DEFAULT '0001-01-01 00:00:00' COMMENT '更新时间',
  PRIMARY KEY(id)
)CHARACTER SET UTF8 COMMENT '用户表';